### ISSUE TITLE
Cura 2.7 - Sigma Vitamins not working

### ISSUE THREAD

**Issue by WanaGo** [BCN3D/BCN3D-Utilities#2]
Hello,
Can I please request Sigma Vitamins for Cura 2.7 to be updated. It has many nice new features, but things like the 'Fix First Extrusion' are failing to work correctly, as I believe the gcode has a few extra 'blank' spaces so the python is not picking up what it is looking for.
There may be other things which have also broken.
Thank you.

**Comment by guillemavila** [comment]
Working on it!

**Comment by guillemavila** [comment]
New files uploaded and should be working now (Build 18JH2019)

**Comment by WanaGo** [comment]
Thanks very much - Trying this out now.
http://goo.gl/BKDE3l

Can I ask, why is it the releases go onto to google drive, rather than under Github, so changes can be seen and tracked? Just curious :)

**Comment by guillemavila** [comment]
Actually all changes can be tracked under the [Sigma ProGen repo](https://github.com/BCN3D/BCN3DSigma-Profile-Generator/tree/Development)

The first approach was just to create some patch files for Ultimaker's Cura to add the Sigma and allow our users to beta test (while we are developing our BCN3D Cura which includes everything by default). 
Then it was easier for most of them to download the files over google drive than github, as on github you had to download the whole utilities repo every time. 
From there we kept updating the same file in drive and linked it to the Utilities repo. Now that we have a quite stable version we'll probably post the raw files here.

Anyways all the changes are visible under the ProGen repo, as all the files are generated by the ProGen engine. We take all these files as a full profile for Cura 2 and that's why it seemed better to keep it under our tool for profile making. On the other hand we had to keep the information up to date for those who knew the Utilities repo and the Cura 2 folder.

I updated the readme of the Cura 2 folder explaining it.
Hope it's clearer now, and thanks for testing ;)
